FROM arm32v7/postgres:10.1


RUN (echo "deb http://ftp.fr.debian.org/debian/ sid main" > /etc/apt/sources.list.d/sid.list ) && \
    apt-get update && \
    apt-get install -y postgresql-$PG_MAJOR postgresql-$PG_MAJOR-postgis-2.4 postgresql-$PG_MAJOR-pgrouting && \
    rm -rf /var/lib/apt/lists/*
